# Generated by Django 5.0.3 on 2026-06-22 04:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Setting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "settings",
            },
        ),
        migrations.CreateModel(
            name="ExtensionInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extension_id", models.CharField(max_length=120, unique=True)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("source", models.CharField(default="filesystem", max_length=32)),
                ("enabled", models.BooleanField(default=True)),
                ("installed", models.BooleanField(default=True)),
                ("booted", models.BooleanField(default=True)),
                ("meta", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "extension_installations",
                "ordering": ["extension_id"],
                "indexes": [
                    models.Index(
                        fields=["enabled"], name="extension_i_enabled_28cd11_idx"
                    ),
                    models.Index(
                        fields=["installed"], name="extension_i_install_66f4a9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "target_type",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("target_id", models.IntegerField(blank=True, null=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                ("data", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "audit_logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["user"], name="audit_logs_user_id_73c422_idx"),
                    models.Index(
                        fields=["action"], name="audit_logs_action_31f574_idx"
                    ),
                    models.Index(
                        fields=["target_type", "target_id"],
                        name="audit_logs_target__9fc8de_idx",
                    ),
                    models.Index(
                        fields=["created_at"], name="audit_logs_created_262184_idx"
                    ),
                ],
            },
        ),
    ]
