from __future__ import annotations

from importlib import import_module
from typing import Any


_EXPORT_MODULES = {
    "AdminNavigationExtender": "bias_core.extensions.extenders_forum_admin",
    "AdminPageDefinition": "bias_core.extensions.sdk",
    "AdminSurfaceExtender": "bias_core.extensions.extenders_forum_admin",
    "ApiResourceExtender": "bias_core.extensions.extenders_resources",
    "ApiRoutesExtender": "bias_core.extensions.extenders_routes_policy",
    "AuthorizationDecision": "bias_core.authorization",
    "AuthorizationPolicy": "bias_core.authorization",
    "AuthExtender": "bias_core.extensions.extenders_system",
    "ConditionalExtender": "bias_core.extensions.extenders_routes_policy",
    "ConsoleExtender": "bias_core.extensions.extenders_system",
    "CsrfExtender": "bias_core.extensions.extenders_system",
    "DatabaseResource": "bias_core.extensions.sdk",
    "DiscussionLifecycleExtender": "bias_core.extensions.extenders_forum_admin",
    "DiscussionListFilterDefinition": "bias_core.extensions.sdk",
    "DiscussionListQueryDefinition": "bias_core.extensions.sdk",
    "DiscussionSortDefinition": "bias_core.extensions.sdk",
    "ErrorHandlingExtender": "bias_core.extensions.extenders_system",
    "EventListenersExtender": "bias_core.extensions.extenders_runtime",
    "ExtensionAdminActionDefinition": "bias_core.extensions.sdk",
    "ExtensionEventListenerDefinition": "bias_core.extensions.sdk",
    "ExtensionManifestRuntimeActionDefinition": "bias_core.extensions.sdk",
    "ExtensionManifestSettingFieldDefinition": "bias_core.extensions.sdk",
    "ExtensionModelCastDefinition": "bias_core.extensions.sdk",
    "ExtensionModelDefaultDefinition": "bias_core.extensions.sdk",
    "ExtensionModelDefinition": "bias_core.extensions.sdk",
    "ExtensionModelRelationDefinition": "bias_core.extensions.sdk",
    "ExtensionModelSlugDriverDefinition": "bias_core.extensions.sdk",
    "ExtensionModelVisibilityDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceEndpointDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceFieldDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceFieldMutatorDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceFilterDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceObjectDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceRelationshipDefinition": "bias_core.extensions.sdk",
    "ExtensionResourceSortDefinition": "bias_core.extensions.sdk",
    "ExtensionRuntimeActionDefinition": "bias_core.extensions.sdk",
    "ExtensionSearchDriverDefinition": "bias_core.extensions.sdk",
    "ExtensionSearchIndexDefinition": "bias_core.extensions.sdk",
    "ExtensionSignalDefinition": "bias_core.extensions.sdk",
    "FilesystemExtender": "bias_core.extensions.extenders_system",
    "FormatterExtender": "bias_core.extensions.extenders_frontend",
    "ForumCapabilitiesExtender": "bias_core.extensions.extenders_forum_admin",
    "ForumPermissionExtender": "bias_core.extensions.extenders_forum_admin",
    "FrontendExtender": "bias_core.extensions.extenders_frontend",
    "LanguagePackDefinition": "bias_core.extensions.sdk",
    "LanguagePackExtender": "bias_core.extensions.extenders_frontend",
    "LifecycleExtender": "bias_core.extensions.extenders_lifecycle",
    "LifecycleInterface": "bias_core.extensions.extenders_lifecycle",
    "LinkExtender": "bias_core.extensions.extenders_frontend",
    "LocalesExtender": "bias_core.extensions.extenders_frontend",
    "MiddlewareExtender": "bias_core.extensions.extenders_routes_policy",
    "ModelExtender": "bias_core.extensions.extenders_model_search",
    "ModelPrivateExtender": "bias_core.extensions.extenders_model_search",
    "ModelUrlExtender": "bias_core.extensions.extenders_model_search",
    "ModelVisibilityExtender": "bias_core.extensions.extenders_model_search",
    "NotificationBlueprint": "bias_core.extensions.notifications",
    "NotificationTypeDefinition": "bias_core.extensions.sdk",
    "NotificationsExtender": "bias_core.extensions.extenders_forum_admin",
    "PermissionDefinition": "bias_core.extensions.sdk",
    "PolicyExtender": "bias_core.extensions.extenders_routes_policy",
    "PostEventExtender": "bias_core.extensions.extenders_system",
    "PostExtender": "bias_core.extensions.extenders_forum_admin",
    "PostLifecycleExtender": "bias_core.extensions.extenders_forum_admin",
    "PostTypeDefinition": "bias_core.extensions.sdk",
    "RealtimeExtender": "bias_core.extensions.extenders_runtime",
    "ResourceDefinition": "bias_core.extensions.sdk",
    "ResourceEndpoint": "bias_core.extensions.sdk",
    "ResourceEndpointDefinition": "bias_core.extensions.sdk",
    "ResourceField": "bias_core.extensions.sdk",
    "ResourceFieldDefinition": "bias_core.extensions.sdk",
    "ResourceFieldMutatorDefinition": "bias_core.extensions.sdk",
    "ResourceFilter": "bias_core.extensions.sdk",
    "ResourceFilterDefinition": "bias_core.extensions.sdk",
    "ResourceRelationship": "bias_core.extensions.sdk",
    "ResourceRelationshipDefinition": "bias_core.extensions.sdk",
    "ResourceSort": "bias_core.extensions.sdk",
    "ResourceSortDefinition": "bias_core.extensions.sdk",
    "RoutesExtender": "bias_core.extensions.extenders_routes_policy",
    "RuntimeActionsExtender": "bias_core.extensions.extenders_forum_admin",
    "RuntimeModel": "bias_core.extensions.extenders_model_search",
    "RuntimeServiceContractExtender": "bias_core.extensions.extenders_system",
    "call_runtime_service": "bias_core.extensions.runtime",
    "SearchDriverExtender": "bias_core.extensions.extenders_model_search",
    "SearchFilterDefinition": "bias_core.extensions.sdk",
    "SearchIndexExtender": "bias_core.extensions.extenders_model_search",
    "ServiceProviderExtender": "bias_core.extensions.extenders_system",
    "SessionExtender": "bias_core.extensions.extenders_system",
    "SettingsExtender": "bias_core.extensions.extenders_forum_admin",
    "SignalExtender": "bias_core.extensions.extenders_runtime",
    "ThemeExtender": "bias_core.extensions.extenders_system",
    "ThrottleApiExtender": "bias_core.extensions.extenders_system",
    "UserExtender": "bias_core.extensions.extenders_forum_admin",
    "UserPreferenceDefinition": "bias_core.extensions.sdk",
    "ViewExtender": "bias_core.extensions.extenders_runtime",
    "WebSocketRoutesExtender": "bias_core.extensions.extenders_routes_policy",
    "admin_action": "bias_core.extensions.sdk",
    "allow": "bias_core.authorization",
    "assert_can": "bias_core.authorization",
    "can": "bias_core.authorization",
    "deny": "bias_core.authorization",
    "event_listener": "bias_core.extensions.sdk",
    "force_allow": "bias_core.authorization",
    "force_deny": "bias_core.authorization",
    "get_enabled_theme": "bias_core.extensions.platform",
    "get_runtime_model": "bias_core.extensions.runtime",
    "get_runtime_service": "bias_core.extensions.runtime",
    "get_runtime_service_value": "bias_core.extensions.runtime",
    "get_theme_settings": "bias_core.extensions.platform",
    "require_runtime_service": "bias_core.extensions.runtime",
    "runtime_action": "bias_core.extensions.sdk",
    "setting_field": "bias_core.extensions.sdk",
}

_SUBMODULES = {
    "contracts",
    "event_bus",
    "formatter_service",
    "frontend_runtime_service",
    "forum",
    "locale_service",
    "manifest",
    "platform",
    "runtime",
    "sdk",
}

__all__ = sorted(_EXPORT_MODULES)


def __getattr__(name: str) -> Any:
    module_name = _EXPORT_MODULES.get(name)
    if module_name:
        value = getattr(import_module(module_name), name)
        globals()[name] = value
        return value

    if name in _SUBMODULES:
        module = import_module(f"{__name__}.{name}")
        globals()[name] = module
        return module

    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
